/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshop;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class BookCategories extends javax.swing.JFrame {

    /**
     * Creates new form BookCategories
     */
    
    boolean action;
    String oldBookCategoryName;
    
    public BookCategories() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblBookCategories = new javax.swing.JLabel();
        lblBookCategoryName = new javax.swing.JLabel();
        txtBookCategoryName = new javax.swing.JTextField();
        btnAddBookCategory = new javax.swing.JButton();
        btnDeleteBookCategory = new javax.swing.JButton();
        btnUpdateBookCategory = new javax.swing.JButton();
        btnSaveBookCategory = new javax.swing.JButton();
        lblFindBookCategory = new javax.swing.JLabel();
        txtFindBookCategory = new javax.swing.JTextField();
        btnFindBookCategory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBookCategories = new javax.swing.JTable();
        btnCloseWindow = new javax.swing.JButton();
        btnShowAllBookCategories = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Book Categories");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblBookCategories.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lblBookCategories.setForeground(java.awt.Color.darkGray);
        lblBookCategories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookCategories.setText("BOOK CATEGORIES");

        lblBookCategoryName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBookCategoryName.setForeground(java.awt.Color.darkGray);
        lblBookCategoryName.setText("Book category name:");

        txtBookCategoryName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAddBookCategory.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddBookCategory.setForeground(java.awt.Color.darkGray);
        btnAddBookCategory.setText("Add Book Category");
        btnAddBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookCategoryActionPerformed(evt);
            }
        });

        btnDeleteBookCategory.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDeleteBookCategory.setForeground(java.awt.Color.darkGray);
        btnDeleteBookCategory.setText("Delete Book Category");
        btnDeleteBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookCategoryActionPerformed(evt);
            }
        });

        btnUpdateBookCategory.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdateBookCategory.setForeground(java.awt.Color.darkGray);
        btnUpdateBookCategory.setText("Update Book Category");
        btnUpdateBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookCategoryActionPerformed(evt);
            }
        });

        btnSaveBookCategory.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSaveBookCategory.setForeground(java.awt.Color.darkGray);
        btnSaveBookCategory.setText("Save Book Category");
        btnSaveBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBookCategoryActionPerformed(evt);
            }
        });

        lblFindBookCategory.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblFindBookCategory.setForeground(java.awt.Color.darkGray);
        lblFindBookCategory.setText("Find book category:");

        txtFindBookCategory.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnFindBookCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFindBookCategory.setForeground(java.awt.Color.orange);
        btnFindBookCategory.setText("Find Book Category!");
        btnFindBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindBookCategoryActionPerformed(evt);
            }
        });

        tableBookCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Book category name"
            }
        ));
        tableBookCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookCategoriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBookCategories);

        btnCloseWindow.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCloseWindow.setForeground(java.awt.Color.blue);
        btnCloseWindow.setText("CLOSE WINDOW");
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        btnShowAllBookCategories.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnShowAllBookCategories.setForeground(java.awt.Color.darkGray);
        btnShowAllBookCategories.setText("Show All Book Categories");
        btnShowAllBookCategories.setToolTipText("");
        btnShowAllBookCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllBookCategoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblBookCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookCategoryName)
                            .addComponent(lblFindBookCategory))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBookCategoryName)
                            .addComponent(txtFindBookCategory)
                            .addComponent(btnFindBookCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowAllBookCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateBookCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddBookCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaveBookCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteBookCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBookCategories)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBookCategoryName)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtBookCategoryName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFindBookCategory)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFindBookCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdateBookCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSaveBookCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnShowAllBookCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFindBookCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddBookCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteBookCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addComponent(btnCloseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void RetrieveData(String sql) {
        String header[] = {"Book category name"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);        
        try {
            Vector data = null;
            tblModel.setRowCount(0);
            ConnectionToDatabase ketNoi = new ConnectionToDatabase();
            ResultSet resultSet = ketNoi.Query(sql);
            while (resultSet.next()) {
                data = new Vector();
                data.add(resultSet.getString("Book category name"));
                
                tblModel.addRow(data);
            }
        tableBookCategories.setModel(tblModel);
        } catch (Exception ex) {
            System.out.println("Error!" + ex);
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql = "SELECT * FROM [Book Category]";
        RetrieveData(sql);
    }//GEN-LAST:event_formWindowOpened

    private void tableBookCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookCategoriesMouseClicked
        String bookCategoryName;
        
        bookCategoryName = tableBookCategories.getValueAt(tableBookCategories.getSelectedRow(), 0).toString();
        txtBookCategoryName.setText(bookCategoryName);
    }//GEN-LAST:event_tableBookCategoriesMouseClicked

    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWindowActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseWindowActionPerformed

    private void btnSaveBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBookCategoryActionPerformed
        String sql;
        String bookCategoryName;
        
        bookCategoryName = txtBookCategoryName.getText();
        
        if (action == true) {
            sql = "INSERT INTO [Book Category] VALUES (N'" + bookCategoryName + "')";
        } else {
            sql = "UPDATE [Book Category] SET [Book category name] = N'" + bookCategoryName + "' WHERE [Book category name] = N'" + oldBookCategoryName + "'";
        }
        
        ConnectionToDatabase ketNoi = new ConnectionToDatabase();
        ketNoi.Update(sql);
        sql = "SELECT * FROM [Book Category]";
        RetrieveData(sql);
        btnAddBookCategory.setEnabled(true);
        btnUpdateBookCategory.setEnabled(true);
        btnSaveBookCategory.setEnabled(false);
    }//GEN-LAST:event_btnSaveBookCategoryActionPerformed

    private void btnAddBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookCategoryActionPerformed
        txtBookCategoryName.setEnabled(true);
        btnAddBookCategory.setEnabled(false);
        btnUpdateBookCategory.setEnabled(false);
        btnDeleteBookCategory.setEnabled(false);
        action = true;
        btnSaveBookCategory.setEnabled(true);
    }//GEN-LAST:event_btnAddBookCategoryActionPerformed

    private void btnUpdateBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookCategoryActionPerformed
        action = false;
        txtBookCategoryName.setEnabled(true);
        btnAddBookCategory.setEnabled(false);
        btnUpdateBookCategory.setEnabled(false);
        btnSaveBookCategory.setEnabled(true);
        oldBookCategoryName = txtBookCategoryName.getText();
    }//GEN-LAST:event_btnUpdateBookCategoryActionPerformed

    private void btnDeleteBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookCategoryActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm to delete Book Category?", "Delete Book Category", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String bookCategoryName;
            bookCategoryName = tableBookCategories.getValueAt(tableBookCategories.getSelectedRow(), 0).toString();
            String sql = "DELETE FROM [Book Category] WHERE [Book category name] = N'" + bookCategoryName + "'";
            ConnectionToDatabase ketNoi = new ConnectionToDatabase();
            ketNoi.Update(sql);
            sql = "SELECT * FROM [Book Category]";
            RetrieveData(sql);
        }
    }//GEN-LAST:event_btnDeleteBookCategoryActionPerformed

    private void btnFindBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindBookCategoryActionPerformed
        String sql = "";
        String keyWord = "";
        keyWord = txtFindBookCategory.getText();
        sql = "SELECT * FROM [Book Category] WHERE [Book category name] LIKE '%" + keyWord + "%'";
        RetrieveData(sql);
    }//GEN-LAST:event_btnFindBookCategoryActionPerformed

    private void btnShowAllBookCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllBookCategoriesActionPerformed
        String sql = "SELECT * FROM [Book Category]";
        RetrieveData(sql);
    }//GEN-LAST:event_btnShowAllBookCategoriesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookCategories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBookCategory;
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnDeleteBookCategory;
    private javax.swing.JButton btnFindBookCategory;
    private javax.swing.JButton btnSaveBookCategory;
    private javax.swing.JButton btnShowAllBookCategories;
    private javax.swing.JButton btnUpdateBookCategory;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBookCategories;
    private javax.swing.JLabel lblBookCategoryName;
    private javax.swing.JLabel lblFindBookCategory;
    private javax.swing.JTable tableBookCategories;
    private javax.swing.JTextField txtBookCategoryName;
    private javax.swing.JTextField txtFindBookCategory;
    // End of variables declaration//GEN-END:variables
}
