/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshop;

import javafx.scene.control.PasswordField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Hieu
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBookShop = new javax.swing.JLabel();
        pnlBookShop = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogIn = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pwfPassword = new javax.swing.JPasswordField();
        chkbShowPassword = new javax.swing.JCheckBox();
        btnExitProgram = new javax.swing.JButton();
        mnbarMainMenu = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuItemLogIn = new javax.swing.JMenuItem();
        MenuItemBrowseBooks = new javax.swing.JMenuItem();
        MenuItemBrowseBookCategories = new javax.swing.JMenuItem();
        MenuItemExitProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOK SHOP");
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(930, 790));

        lblBookShop.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        lblBookShop.setForeground(java.awt.Color.orange);
        lblBookShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookShop.setText("BOOK SHOP");

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblUsername.setForeground(java.awt.Color.darkGray);
        lblUsername.setText("USERNAME:");

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblPassword.setForeground(java.awt.Color.darkGray);
        lblPassword.setText("PASSWORD:");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnLogIn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnLogIn.setForeground(java.awt.Color.darkGray);
        btnLogIn.setText("LOG IN!");
        btnLogIn.setToolTipText("");
        btnLogIn.setActionCommand("");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnReset.setForeground(java.awt.Color.darkGray);
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        pwfPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pwfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        chkbShowPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chkbShowPassword.setForeground(java.awt.Color.darkGray);
        chkbShowPassword.setText("SHOW PASSWORD");
        chkbShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbShowPasswordActionPerformed(evt);
            }
        });

        btnExitProgram.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnExitProgram.setForeground(java.awt.Color.darkGray);
        btnExitProgram.setText("EXIT PROGRAM");
        btnExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBookShopLayout = new javax.swing.GroupLayout(pnlBookShop);
        pnlBookShop.setLayout(pnlBookShopLayout);
        pnlBookShopLayout.setHorizontalGroup(
            pnlBookShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookShopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addGroup(pnlBookShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername)
                    .addGroup(pnlBookShopLayout.createSequentialGroup()
                        .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                    .addComponent(pwfPassword)
                    .addGroup(pnlBookShopLayout.createSequentialGroup()
                        .addComponent(chkbShowPassword)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnExitProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBookShopLayout.setVerticalGroup(
            pnlBookShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookShopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlBookShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwfPassword))
                .addGap(18, 18, 18)
                .addComponent(chkbShowPassword)
                .addGap(18, 18, 18)
                .addGroup(pnlBookShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        MenuFile.setText("MAIN MENU");

        MenuItemLogIn.setText("Log In");
        MenuItemLogIn.setToolTipText("");
        MenuItemLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogInActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemLogIn);

        MenuItemBrowseBooks.setText("Browse Books");
        MenuItemBrowseBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBrowseBooksActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemBrowseBooks);

        MenuItemBrowseBookCategories.setText("Browse Book Categories");
        MenuItemBrowseBookCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBrowseBookCategoriesActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemBrowseBookCategories);

        MenuItemExitProgram.setText("Exit Program");
        MenuItemExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitProgramActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemExitProgram);

        mnbarMainMenu.add(MenuFile);

        setJMenuBar(mnbarMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBookShop, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(pnlBookShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBookShop)
                .addGap(18, 18, 18)
                .addComponent(pnlBookShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitProgramActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Exit program?", "Exit Program", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            System.exit(0);
        }        
    }//GEN-LAST:event_MenuItemExitProgramActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        if (txtUsername.getText().equals("admin") && pwfPassword.getText().equals("admin") && txtUsername.getText() != null && pwfPassword.getText() != null) {
            BookShopWindow bookShopWindow = new BookShopWindow();
            bookShopWindow.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Wrong username or password!\nTry again!", "Wrong username or password", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtUsername.setText("");
        pwfPassword.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void MenuItemLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogInActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_MenuItemLogInActionPerformed

    private void chkbShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbShowPasswordActionPerformed
        if (chkbShowPassword.isSelected()) {
            pwfPassword.setEchoChar((char)0);
        } else {
            pwfPassword.setEchoChar('●');
        }
    }//GEN-LAST:event_chkbShowPasswordActionPerformed

    private void btnExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitProgramActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Exit program?", "Exit Program", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitProgramActionPerformed

    private void MenuItemBrowseBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBrowseBooksActionPerformed
        BrowseBooks browseBooks = new BrowseBooks();
        browseBooks.setVisible(true);
    }//GEN-LAST:event_MenuItemBrowseBooksActionPerformed

    private void MenuItemBrowseBookCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBrowseBookCategoriesActionPerformed
        BrowseBookCategories browseBookCategories = new BrowseBookCategories();
        browseBookCategories.setVisible(true);
    }//GEN-LAST:event_MenuItemBrowseBookCategoriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuItemBrowseBookCategories;
    private javax.swing.JMenuItem MenuItemBrowseBooks;
    private javax.swing.JMenuItem MenuItemExitProgram;
    private javax.swing.JMenuItem MenuItemLogIn;
    private javax.swing.JButton btnExitProgram;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkbShowPassword;
    private javax.swing.JLabel lblBookShop;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenuBar mnbarMainMenu;
    private javax.swing.JPanel pnlBookShop;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
