/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshop;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    boolean action;
    public Orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrders = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        lblOrderDate = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        btnShowAllOrders = new javax.swing.JButton();
        btnAddNewOrder = new javax.swing.JButton();
        btnUpdateOrder = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnSaveOrder = new javax.swing.JButton();
        lblFindByOrderID = new javax.swing.JLabel();
        txtFindByOrderID = new javax.swing.JTextField();
        btnCloseWindow = new javax.swing.JButton();
        btnFindOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrders = new javax.swing.JTable();
        btnDeleteOrder = new javax.swing.JButton();
        lblBookID = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Customers' Orders");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblOrders.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lblOrders.setForeground(java.awt.Color.darkGray);
        lblOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrders.setText("ORDERS");

        lblOrderID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblOrderID.setForeground(java.awt.Color.darkGray);
        lblOrderID.setText("Order ID:");

        txtOrderID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblCustomerID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCustomerID.setForeground(java.awt.Color.darkGray);
        lblCustomerID.setText("Customer ID:");

        txtCustomerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblOrderDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblOrderDate.setForeground(java.awt.Color.darkGray);
        lblOrderDate.setText("Order Date:");

        txtOrderDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnShowAllOrders.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnShowAllOrders.setForeground(java.awt.Color.darkGray);
        btnShowAllOrders.setText("Show All Orders");
        btnShowAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllOrdersActionPerformed(evt);
            }
        });

        btnAddNewOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddNewOrder.setForeground(java.awt.Color.darkGray);
        btnAddNewOrder.setText("Add New Order");
        btnAddNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewOrderActionPerformed(evt);
            }
        });

        btnUpdateOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdateOrder.setForeground(java.awt.Color.darkGray);
        btnUpdateOrder.setText("Update Order");
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTotal.setForeground(java.awt.Color.darkGray);
        lblTotal.setText("Total:");

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSaveOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSaveOrder.setForeground(java.awt.Color.darkGray);
        btnSaveOrder.setText("Save Order");

        lblFindByOrderID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFindByOrderID.setForeground(java.awt.Color.darkGray);
        lblFindByOrderID.setText("Enter Order ID:");

        txtFindByOrderID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCloseWindow.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnCloseWindow.setForeground(java.awt.Color.blue);
        btnCloseWindow.setText("CLOSE WINDOW");
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        btnFindOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFindOrder.setForeground(java.awt.Color.orange);
        btnFindOrder.setText("Find Order!");
        btnFindOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOrderActionPerformed(evt);
            }
        });

        tableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer ID", "Order Date", "Book ID", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableOrders);

        btnDeleteOrder.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDeleteOrder.setForeground(java.awt.Color.darkGray);
        btnDeleteOrder.setText("Delete Order");
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });

        lblBookID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBookID.setForeground(java.awt.Color.darkGray);
        lblBookID.setText("Book ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomerID)
                            .addComponent(lblOrderID)
                            .addComponent(lblOrderDate)
                            .addComponent(lblTotal)
                            .addComponent(lblBookID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFindOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFindByOrderID)
                                .addGap(18, 18, 18)
                                .addComponent(txtFindByOrderID))
                            .addComponent(txtOrderDate)
                            .addComponent(txtOrderID)
                            .addComponent(txtCustomerID)
                            .addComponent(txtTotal)
                            .addComponent(txtBookID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowAllOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addComponent(btnAddNewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrders)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowAllOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOrderID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddNewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCustomerID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOrderDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBookID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSaveOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFindByOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFindByOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnFindOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void RetrieveData(String sql) {
        String header[] = {"Order ID", "Customer ID", "Order date","Book ID", "Total"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        try {
            Vector data = null;
            tblModel.setRowCount(0);
            ConnectionToDatabase kn = new ConnectionToDatabase();
            ResultSet rs = kn.Query(sql);
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString("Order ID"));
                data.add(rs.getString("Customer ID"));
                data.add(rs.getString("Order date"));
                data.add(rs.getString("Book ID"));
                data.add(rs.getDouble("Total"));
                
                tblModel.addRow(data);
            }
        tableOrders.setModel(tblModel);
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql = "SELECT * FROM [Order]";
        RetrieveData(sql);
    }//GEN-LAST:event_formWindowOpened

    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWindowActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseWindowActionPerformed

    private void btnShowAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllOrdersActionPerformed
        String sql = "SELECT * FROM [Order]";
        RetrieveData(sql);
    }//GEN-LAST:event_btnShowAllOrdersActionPerformed

    private void btnUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderActionPerformed
        action = false;
        txtOrderID.setEnabled(false);
        btnAddNewOrder.setEnabled(false);
        btnUpdateOrder.setEnabled(false);
        btnSaveOrder.setEnabled(true);
    }//GEN-LAST:event_btnUpdateOrderActionPerformed

    private void btnAddNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewOrderActionPerformed
        txtOrderID.setEnabled(true);
        txtOrderID.setText("");
        txtCustomerID.setText("");
        txtOrderDate.setText("");
        txtTotal.setText("");
        btnAddNewOrder.setEnabled(false);
        btnUpdateOrder.setEnabled(false);
        action = true;
        btnSaveOrder.setEnabled(true);
    }//GEN-LAST:event_btnAddNewOrderActionPerformed

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm to delete order?", "Delete Order", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String orderID;
            orderID = tableOrders.getValueAt(tableOrders.getSelectedRow(), 0).toString();
            String sql = "DELETE FROM [Order] WHERE [Order ID] = N'" + orderID + "'";
            ConnectionToDatabase ketNoi = new ConnectionToDatabase();
            ketNoi.Update(sql);
            sql = "SELECT * FROM [Order]";
            RetrieveData(sql);
        }
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private void btnFindOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindOrderActionPerformed
        String sql = "";
        String keyWord = txtFindByOrderID.getText();
        sql = "SELECT * FROM [Order] WHERE [Order ID] LIKE '%" + keyWord + "%'";
        RetrieveData(sql);
    }//GEN-LAST:event_btnFindOrderActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewOrder;
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnFindOrder;
    private javax.swing.JButton btnSaveOrder;
    private javax.swing.JButton btnShowAllOrders;
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBookID;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblFindByOrderID;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrders;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tableOrders;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtFindByOrderID;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
