/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshop;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieu
 */
public class PublishingCompanies extends javax.swing.JFrame {

    /**
     * Creates new form PublishingCompanies
     */
    public PublishingCompanies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    boolean action;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblPublishingCompanies = new javax.swing.JLabel();
        lblPublishingCompanyName = new javax.swing.JLabel();
        txtPublishingCompanyName = new javax.swing.JTextField();
        lblPublishingCompanyAddress = new javax.swing.JLabel();
        txtPublishingCompanyAddress = new javax.swing.JTextField();
        lblPublishingCompanyPhoneNumber = new javax.swing.JLabel();
        txtPublishingCompanyPhoneNumber = new javax.swing.JTextField();
        lblPubishingCompanyEmail = new javax.swing.JLabel();
        txtPublishingCompanyEmail = new javax.swing.JTextField();
        btnShowAllPublishingCompanies = new javax.swing.JButton();
        btnAddNewPublishingCompany = new javax.swing.JButton();
        btnUpdatePublishingCompany = new javax.swing.JButton();
        btnDeletePublishingCompany = new javax.swing.JButton();
        btnSavePublishingCompany = new javax.swing.JButton();
        txtFindPublishingCompany = new javax.swing.JTextField();
        btnFindPublishingCompany = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCloseWindow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePublishingCompanies = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Publishing Companies");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblPublishingCompanies.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        lblPublishingCompanies.setForeground(java.awt.Color.darkGray);
        lblPublishingCompanies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPublishingCompanies.setText("PUBLISHING COMPANIES");

        lblPublishingCompanyName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPublishingCompanyName.setForeground(java.awt.Color.darkGray);
        lblPublishingCompanyName.setText("Publishing company name:");

        txtPublishingCompanyName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblPublishingCompanyAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPublishingCompanyAddress.setForeground(java.awt.Color.darkGray);
        lblPublishingCompanyAddress.setText("Address:");

        txtPublishingCompanyAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblPublishingCompanyPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPublishingCompanyPhoneNumber.setForeground(java.awt.Color.darkGray);
        lblPublishingCompanyPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPublishingCompanyPhoneNumber.setText("Phone number:");

        txtPublishingCompanyPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblPubishingCompanyEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPubishingCompanyEmail.setForeground(java.awt.Color.darkGray);
        lblPubishingCompanyEmail.setText("Email:");

        txtPublishingCompanyEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnShowAllPublishingCompanies.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnShowAllPublishingCompanies.setForeground(java.awt.Color.darkGray);
        btnShowAllPublishingCompanies.setText("Show All Publishing Companies");
        btnShowAllPublishingCompanies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllPublishingCompaniesActionPerformed(evt);
            }
        });

        btnAddNewPublishingCompany.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddNewPublishingCompany.setForeground(java.awt.Color.darkGray);
        btnAddNewPublishingCompany.setText("Add New Publishing Company");
        btnAddNewPublishingCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPublishingCompanyActionPerformed(evt);
            }
        });

        btnUpdatePublishingCompany.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdatePublishingCompany.setForeground(java.awt.Color.darkGray);
        btnUpdatePublishingCompany.setText("Update Publishing Company");
        btnUpdatePublishingCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePublishingCompanyActionPerformed(evt);
            }
        });

        btnDeletePublishingCompany.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDeletePublishingCompany.setForeground(java.awt.Color.darkGray);
        btnDeletePublishingCompany.setText("Delete Publishing Company");
        btnDeletePublishingCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePublishingCompanyActionPerformed(evt);
            }
        });

        btnSavePublishingCompany.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSavePublishingCompany.setForeground(java.awt.Color.darkGray);
        btnSavePublishingCompany.setText("Save Publishing Company");
        btnSavePublishingCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePublishingCompanyActionPerformed(evt);
            }
        });

        txtFindPublishingCompany.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnFindPublishingCompany.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFindPublishingCompany.setForeground(java.awt.Color.orange);
        btnFindPublishingCompany.setText("Find Publishing Company!");
        btnFindPublishingCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPublishingCompanyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.darkGray);
        jLabel1.setText("Enter key word:");

        btnCloseWindow.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCloseWindow.setForeground(java.awt.Color.blue);
        btnCloseWindow.setText("CLOSE WINDOW");
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        tablePublishingCompanies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Publishing Company ID", "Company Name", "Address", "Phone Number", "Email"
            }
        ));
        tablePublishingCompanies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePublishingCompaniesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePublishingCompanies);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPublishingCompanies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnFindPublishingCompany, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFindPublishingCompany, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPublishingCompanyName)
                                    .addComponent(lblPublishingCompanyAddress)
                                    .addComponent(lblPubishingCompanyEmail)
                                    .addComponent(lblPublishingCompanyPhoneNumber))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPublishingCompanyAddress)
                                    .addComponent(txtPublishingCompanyPhoneNumber)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPublishingCompanyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtPublishingCompanyName, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowAllPublishingCompanies, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(btnAddNewPublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdatePublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletePublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSavePublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPublishingCompanies)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShowAllPublishingCompanies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddNewPublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdatePublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletePublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPublishingCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPublishingCompanyName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPublishingCompanyAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPublishingCompanyAddress))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPublishingCompanyPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPublishingCompanyPhoneNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPubishingCompanyEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPublishingCompanyEmail))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFindPublishingCompany)
                    .addComponent(btnSavePublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnFindPublishingCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void RetrieveData(String sql) {
        String header[] = {"Publishing company name", "Address", "Phone number", "Email"};
        DefaultTableModel tblModel = new DefaultTableModel(header, 0);
        try {
            Vector data = null;
            tblModel.setRowCount(0);
            ConnectionToDatabase ketNoi = new ConnectionToDatabase();
            ResultSet resultSet = ketNoi.Query(sql);
            while (resultSet.next()) {
                data = new Vector();
                data.add(resultSet.getString("Publishing company name"));
                data.add(resultSet.getString("Address"));
                data.add(resultSet.getString("Phone number"));
                data.add(resultSet.getString("Email"));
                
                tblModel.addRow(data);
            }
        tablePublishingCompanies.setModel(tblModel);
        } catch (Exception ex) {
            System.out.println("Error!" + ex);
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql = "SELECT * FROM [Publishing Company]";
        RetrieveData(sql);
    }//GEN-LAST:event_formWindowOpened

    private void btnShowAllPublishingCompaniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllPublishingCompaniesActionPerformed
        String sql = "SELECT * FROM [Publishing Company]";
        RetrieveData(sql);
    }//GEN-LAST:event_btnShowAllPublishingCompaniesActionPerformed

    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWindowActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseWindowActionPerformed

    private void tablePublishingCompaniesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePublishingCompaniesMouseClicked
        String publishingCompanyName;
        String address;
        String phoneNumber;
        String email;
        
        publishingCompanyName = tablePublishingCompanies.getValueAt(tablePublishingCompanies.getSelectedRow(), 0).toString();
        txtPublishingCompanyName.setText(publishingCompanyName);
        address = tablePublishingCompanies.getValueAt(tablePublishingCompanies.getSelectedRow(), 1).toString();
        txtPublishingCompanyAddress.setText(address);
        phoneNumber = tablePublishingCompanies.getValueAt(tablePublishingCompanies.getSelectedRow(), 2).toString();
        txtPublishingCompanyPhoneNumber.setText(phoneNumber);
        email = tablePublishingCompanies.getValueAt(tablePublishingCompanies.getSelectedRow(), 3).toString();
        txtPublishingCompanyEmail.setText(email);
    }//GEN-LAST:event_tablePublishingCompaniesMouseClicked

    private void btnSavePublishingCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePublishingCompanyActionPerformed
        String sql;
        String publishingCompanyName;
        String address;
        String phoneNumber;
        String email;
        
        publishingCompanyName = txtPublishingCompanyName.getText();
        address = txtPublishingCompanyAddress.getText();
        phoneNumber = txtPublishingCompanyPhoneNumber.getText();
        email = txtPublishingCompanyEmail.getText();
        
        if (action == true) {
            sql = "INSERT INTO [Publishing Company] VALUES (N'" + publishingCompanyName + "', N'" + address + "', N'" + phoneNumber + "', N'" + email + "')";
        } else {
            sql = "UPDATE [Publishing Company] SET [Address] = N'" + address + "', [Phone number] = N'" + phoneNumber + "', [Email] = N'" + email + "' WHERE [Publishing company name] = N'" + publishingCompanyName + "'";
        }
        ConnectionToDatabase ketNoi = new ConnectionToDatabase();
        ketNoi.Update(sql);
        sql = "SELECT * FROM [Publishing Company]";
        RetrieveData(sql);
        btnAddNewPublishingCompany.setEnabled(true);
        btnUpdatePublishingCompany.setEnabled(true);
        btnDeletePublishingCompany.setEnabled(true);
        btnSavePublishingCompany.setEnabled(false);
    }//GEN-LAST:event_btnSavePublishingCompanyActionPerformed

    private void btnAddNewPublishingCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPublishingCompanyActionPerformed
        txtPublishingCompanyName.setEnabled(true);
        txtPublishingCompanyName.setText("");
        txtPublishingCompanyAddress.setText("");
        txtPublishingCompanyPhoneNumber.setText("");
        txtPublishingCompanyEmail.setText("");
        btnAddNewPublishingCompany.setEnabled(false);
        btnUpdatePublishingCompany.setEnabled(false);
        action = true;
        btnSavePublishingCompany.setEnabled(true);
    }//GEN-LAST:event_btnAddNewPublishingCompanyActionPerformed

    private void btnUpdatePublishingCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePublishingCompanyActionPerformed
        action = false;
        txtPublishingCompanyName.setEnabled(false);
        btnAddNewPublishingCompany.setEnabled(false);
        btnUpdatePublishingCompany.setEnabled(false);
        btnSavePublishingCompany.setEnabled(true);
    }//GEN-LAST:event_btnUpdatePublishingCompanyActionPerformed

    private void btnDeletePublishingCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePublishingCompanyActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Confirm to delete Publishing Company?", "Delete Publishing Company", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String publishingCompanyName;
            publishingCompanyName = tablePublishingCompanies.getValueAt(tablePublishingCompanies.getSelectedRow(), 0).toString();
            String sql = "DELETE FROM [Publishing Company] WHERE [Publishing company name] = N'" + publishingCompanyName + "'";
            ConnectionToDatabase ketNoi = new ConnectionToDatabase();
            ketNoi.Update(sql);
            sql = "SELECT * FROM [Publishing Company]";
            RetrieveData(sql);
        }
    }//GEN-LAST:event_btnDeletePublishingCompanyActionPerformed

    private void btnFindPublishingCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPublishingCompanyActionPerformed
        String sql = "";
        String keyWord = "";
        keyWord = txtFindPublishingCompany.getText();
        sql = "SELECT * FROM [Publishing Company] WHERE [Publishing company name] LIKE '%" + keyWord + "%'";
        RetrieveData(sql);        
    }//GEN-LAST:event_btnFindPublishingCompanyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublishingCompanies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublishingCompanies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublishingCompanies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublishingCompanies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PublishingCompanies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewPublishingCompany;
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnDeletePublishingCompany;
    private javax.swing.JButton btnFindPublishingCompany;
    private javax.swing.JButton btnSavePublishingCompany;
    private javax.swing.JButton btnShowAllPublishingCompanies;
    private javax.swing.JButton btnUpdatePublishingCompany;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPubishingCompanyEmail;
    private javax.swing.JLabel lblPublishingCompanies;
    private javax.swing.JLabel lblPublishingCompanyAddress;
    private javax.swing.JLabel lblPublishingCompanyName;
    private javax.swing.JLabel lblPublishingCompanyPhoneNumber;
    private javax.swing.JTable tablePublishingCompanies;
    private javax.swing.JTextField txtFindPublishingCompany;
    private javax.swing.JTextField txtPublishingCompanyAddress;
    private javax.swing.JTextField txtPublishingCompanyEmail;
    private javax.swing.JTextField txtPublishingCompanyName;
    private javax.swing.JTextField txtPublishingCompanyPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
